import { useState, useEffect } from 'react';
import { ArrowRight, Activity, Target, Zap, Clock, FileText } from 'lucide-react';
import { Link } from 'react-router-dom';
import api from '../api/axios';

export default function Dashboard() {
  const [interviewHistory, setInterviewHistory] = useState<any[]>([]);
  const [resumeHistory, setResumeHistory] = useState<any[]>([]);
  const [latestResumeScore, setLatestResumeScore] = useState<number | null>(null);

  useEffect(() => {
    const fetchData = async () => {
      try {
        const interviewRes = await api.get("/interview/history");
        setInterviewHistory(interviewRes.data);
      } catch (err: any) {
        console.error("API Error fetching interview history:", err);
      }

      try {
        const resumeRes = await api.get("/resume/history");
        setResumeHistory(resumeRes.data);
        if (resumeRes.data && resumeRes.data.length > 0) {
          setLatestResumeScore(resumeRes.data[0].ats_score);
        }
      } catch (err: any) {
        console.error("API Error fetching resume history:", err);
      }
    };
    fetchData();
  }, []);

  return (
    <div className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-700">
      <header>
        <h1 className="text-4xl font-bold mb-2">Welcome back, Student</h1>
        <p className="text-muted">Track your interview readiness and placement progress.</p>
      </header>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="glass-panel p-6">
          <div className="w-12 h-12 rounded-full bg-primary/20 flex items-center justify-center text-primary mb-4">
            <Activity size={24} />
          </div>
          <h3 className="text-lg font-semibold mb-1">Latest ATS Score</h3>
          <p className="text-3xl font-bold mb-2">{latestResumeScore !== null ? latestResumeScore : '--'}<span className="text-sm text-muted font-normal">/100</span></p>
          <p className="text-sm text-muted">Keep optimizing for a higher match</p>
        </div>
        
        <div className="glass-panel p-6">
          <div className="w-12 h-12 rounded-full bg-secondary/20 flex items-center justify-center text-secondary mb-4">
            <Target size={24} />
          </div>
          <h3 className="text-lg font-semibold mb-1">Interviews</h3>
          <p className="text-3xl font-bold mb-2">{interviewHistory.length}</p>
          <p className="text-sm text-muted">Mock sessions completed</p>
        </div>

        <div className="glass-panel p-6">
          <div className="w-12 h-12 rounded-full bg-accent/20 flex items-center justify-center text-accent mb-4">
            <Zap size={24} />
          </div>
          <h3 className="text-lg font-semibold mb-1">Skill Gap</h3>
          <p className="text-3xl font-bold mb-2">4</p>
          <p className="text-sm text-muted">Critical skills to improve</p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <div className="glass-panel p-6 relative overflow-hidden group">
          <div className="absolute top-0 right-0 p-8 opacity-10 group-hover:scale-110 transition-transform duration-500">
            <Target size={100} />
          </div>
          <h2 className="text-2xl font-bold mb-4">Prepare for Interviews</h2>
          <p className="text-muted mb-6 max-w-sm">Take a mock interview session generated by AI based on your target domain and difficulty level.</p>
          <Link to="/interview" className="btn-primary inline-flex items-center gap-2">
            Start Mock Interview <ArrowRight size={18} />
          </Link>
        </div>

        <div className="glass-panel p-6 relative overflow-hidden group">
          <div className="absolute top-0 right-0 p-8 opacity-10 group-hover:scale-110 transition-transform duration-500">
            <Activity size={100} />
          </div>
          <h2 className="text-2xl font-bold mb-4">Resume Optimization</h2>
          <p className="text-muted mb-6 max-w-sm">Update your resume now to boost your ATS score and get better recommendations.</p>
          <Link to="/resume" className="btn-secondary inline-flex items-center gap-2">
            Upload New Resume <ArrowRight size={18} />
          </Link>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        <div className="glass-panel p-8">
          <h2 className="text-2xl font-bold mb-6 flex items-center gap-2">
            <FileText size={24} className="text-accent" /> ATS History
          </h2>
          {resumeHistory.length === 0 ? (
            <div className="text-center py-10 bg-white/5 rounded-xl border border-white/10">
              <p className="text-muted mb-4">You haven't analyzed any resumes yet.</p>
              <Link to="/resume" className="text-accent hover:underline">Upload your resume</Link>
            </div>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full text-left border-collapse">
                <thead>
                  <tr className="border-b border-white/10">
                    <th className="p-4 font-semibold text-muted">Date</th>
                    <th className="p-4 font-semibold text-muted">Overall Score</th>
                    <th className="p-4 font-semibold text-muted">Skills Match</th>
                  </tr>
                </thead>
                <tbody>
                  {resumeHistory.map((r, i) => (
                    <tr key={i} className="border-b border-white/5 hover:bg-white/5 transition-colors">
                      <td className="p-4">{new Date(r.uploaded_at).toLocaleDateString()}</td>
                      <td className="p-4">
                        <span className={`px-2 py-1 rounded font-bold text-xs ${r.ats_score >= 80 ? 'bg-green-500/20 text-green-400' : r.ats_score >= 60 ? 'bg-yellow-500/20 text-yellow-400' : 'bg-red-500/20 text-red-400'}`}>
                          {r.ats_score}/100
                        </span>
                      </td>
                      <td className="p-4">{r.skills_match}%</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>

        <div className="glass-panel p-8">
          <h2 className="text-2xl font-bold mb-6 flex items-center gap-2">
            <Clock size={24} className="text-primary" /> Interview History
          </h2>
          {interviewHistory.length === 0 ? (
            <div className="text-center py-10 bg-white/5 rounded-xl border border-white/10">
              <p className="text-muted mb-4">You haven't taken any mock interviews yet.</p>
              <Link to="/interview" className="text-primary hover:underline">Start your first interview</Link>
            </div>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full text-left border-collapse">
                <thead>
                  <tr className="border-b border-white/10">
                    <th className="p-4 font-semibold text-muted">Date</th>
                    <th className="p-4 font-semibold text-muted">Domain</th>
                    <th className="p-4 font-semibold text-muted">Score</th>
                  </tr>
                </thead>
                <tbody>
                  {interviewHistory.map((h, i) => (
                    <tr key={i} className="border-b border-white/5 hover:bg-white/5 transition-colors">
                      <td className="p-4">{new Date(h.date).toLocaleDateString()}</td>
                      <td className="p-4 font-medium">{h.domain}</td>
                      <td className="p-4">
                        <span className={`px-2 py-1 rounded font-bold text-xs ${h.score >= 80 ? 'bg-green-500/20 text-green-400' : h.score >= 60 ? 'bg-yellow-500/20 text-yellow-400' : 'bg-red-500/20 text-red-400'}`}>
                          {h.score}/100
                        </span>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
